linked_words:
  type: objects
  default:
    - pattern: '/(?:DN|Dn|dn)[^\S\r\n]?([1-9]|[12][0-9]|3[0-4])(?:(?![0-9]))/'
      url: 'https://suttacentral.net/dn$1/en/sujato'
    - pattern: '/(?:DN|Dn|dn)[^\S\r\n]?(([1-9]|[12][0-9]|3[0-4]))(:[1-9](?:[0-9-]+)?(?:\.[1-9](?:[0-9-]+)?){1,3})/'
      url: 'https://suttacentral.net/dn$1/en/sujato#dn$2$3'
  schema:
    name: linkify_rule
    properties:
      pattern:
        type: string
        required: true
      url:
        type: string
        required: true
excluded_tags:
  type: list
  list_type: compact
  default: "code|pre"
excluded_classes:
  type: list
  list_type: compact
  default: "onebox"
regex_substitute_or_character:
  default: "¦"
left_word_boundary:
  type: list
  list_type: compact
  default: "\\s|:|.|;|,|!|?|…|(|[|{|“|‘|=|—|–|-|/"
right_word_boundary:
  type: list
  list_type: compact
  default: "\\s|:|.|;|,|!|?|…|}|]|)|”|’|=|—|–|-|/"
