linked_words:
  type: objects
  default:
    - pattern: '/(?:AN|An|an)[^\S\r\n]?([18]\.(?:[1-9]|[1-9][0-9]|[1-5][0-9][0-9]|6[01][0-9]|62[0-7])|2\.(?:[1-9]|[1-9][0-9]|[1-3][0-9][0-9]|4[0-7][0-9])|3\.(?:[1-9]|[1-9][0-9]|[12][0-9][0-9]|3[0-4][0-9]|35[0-2])|4\.(?:[1-9]|[1-9][0-9]|[1-6][0-9][0-9]|7[0-7][0-9]|78[0-3])|5\.(?:[1-9]|[1-9][0-9]|[1-9][0-9][0-9]|10[0-9][0-9]|11[0-4][0-9]|115[0-2])|6\.(?:[1-9]|[1-9][0-9]|[1-5][0-9][0-9]|6[0-4][0-9])|7\.(?:[1-9]|[1-9][0-9]|[1-9][0-9][0-9]|10[0-9][0-9]|11[01][0-9]|112[0-4])|9\.(?:[1-9]|[1-9][0-9]|[1-3][0-9][0-9]|4[0-2][0-9]|43[0-2])|10\.(?:[1-9]|[1-9][0-9]|[1-6][0-9][0-9]|7[0-3][0-9]|74[0-6])|11\.(?:[1-9]|[1-9][0-9]|[1-9][0-9][0-9]|10[0-9][0-9]|11[0-4][0-9]|115[01]))(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/an$1/en/sujato'
    - pattern: '/(?:AN|An|an)[^\S\r\n]?(([18]\.(?:[1-9]|[1-9][0-9]|[1-5][0-9][0-9]|6[01][0-9]|62[0-7])|2\.(?:[1-9]|[1-9][0-9]|[1-3][0-9][0-9]|4[0-7][0-9])|3\.(?:[1-9]|[1-9][0-9]|[12][0-9][0-9]|3[0-4][0-9]|35[0-2])|4\.(?:[1-9]|[1-9][0-9]|[1-6][0-9][0-9]|7[0-7][0-9]|78[0-3])|5\.(?:[1-9]|[1-9][0-9]|[1-9][0-9][0-9]|10[0-9][0-9]|11[0-4][0-9]|115[0-2])|6\.(?:[1-9]|[1-9][0-9]|[1-5][0-9][0-9]|6[0-4][0-9])|7\.(?:[1-9]|[1-9][0-9]|[1-9][0-9][0-9]|10[0-9][0-9]|11[01][0-9]|112[0-4])|9\.(?:[1-9]|[1-9][0-9]|[1-3][0-9][0-9]|4[0-2][0-9]|43[0-2])|10\.(?:[1-9]|[1-9][0-9]|[1-6][0-9][0-9]|7[0-3][0-9]|74[0-6])|11\.(?:[1-9]|[1-9][0-9]|[1-9][0-9][0-9]|10[0-9][0-9]|11[0-4][0-9]|115[01])))(:[1-9](?:[0-9]+)?\.[1-9](?:[0-9]+)?)/'
      url: 'https://suttacentral.net/an$1/en/sujato#an$2$3'
    - pattern: '/(?:AN|An|an)[^\S\r\n]?(?:([1-9]|1[01]):([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|10[0-9][0-9]|11[0-5][0-9]))/'
      url: 'https://suttacentral.net/an$1.$2/en/sujato'
    - pattern: '/(?:DN|Dn|dn)[^\S\r\n]?([1-9]|[12][0-9]|3[0-4])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/dn$1/en/sujato'
    - pattern: '/(?:DN|Dn|dn)[^\S\r\n]?(([1-9]|[12][0-9]|3[0-4]))(:[1-9](?:[0-9-]+)?(?:\.[1-9](?:[0-9-]+)?){1,3})/'
      url: 'https://suttacentral.net/dn$1/en/sujato#dn$2$3'
    - pattern: '/(?:Cp|CP|cp)[^\S\r\n]?([1-9]|[12][0-9]|3[0-5])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/cp$1/en/sujato'
    - pattern: '/(?:Cp|CP|cp)[^\S\r\n]?(([1-9]|[12][0-9]|3[0-5]))(:[1-9](?:[0-9]+)?\.[1-9](?:[0-9]+)?)/'
      url: 'https://suttacentral.net/cp$1/en/sujato#cp$2$3'
    - pattern: '/(?:Dhp|DHP|dhp)[^\S\r\n]?([1-9]|[1-9][0-9]|[1-3][0-9][0-9]|4[01][0-9]|42[0-3])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/dhp$1/en/sujato'
    - pattern: '/(?:Dhp|DHP|dhp)[^\S\r\n]?(([1-9]|[1-9][0-9]|[1-3][0-9][0-9]|4[01][0-9]|42[0-3]))(:[1-9](?:[0-9]+)?\.[1-9](?:[0-9]+)?)/'
      url: 'https://suttacentral.net/dhp$1/en/sujato#dhp$2$3'
    - pattern: '/(?:Iti|ITI|iti)[^\S\r\n]?([1-9]|[1-9][0-9]|10[0-9]|11[0-2])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/iti$1/en/sujato'
    - pattern: '/(?:Iti|ITI|iti)[^\S\r\n]?(([1-9]|[1-9][0-9]|10[0-9]|11[0-2]))(:[1-9](?:[0-9]+)?\.[1-9](?:[0-9]+)?)/'
      url: 'https://suttacentral.net/iti$1/en/sujato#iti$2$3'
    - pattern: '/(?:Ja|JA|ja)[^\S\r\n]?([1-9]|[1-9][0-9]|[1-4][0-9][0-9]|5[0-3][0-9]|54[0-7])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/ja$1/en/sujato'
    - pattern: '/(?:Ja|JA|ja)[^\S\r\n]?(([1-9]|[1-9][0-9]|[1-4][0-9][0-9]|5[0-3][0-9]|54[0-7]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,2})/'
      url: 'https://suttacentral.net/ja$1/en/sujato#ja$2$3'
    - pattern: '/(?:Kp|KP|kp)[^\S\r\n]?(?:([1-9]))(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/kp$1/en/sujato'
    - pattern: '/(?:Kp|KP|kp)[^\S\r\n]?((?:([1-9])))(:[1-9](?:[0-9]+)?\.[1-9](?:[0-9]+)?)/'
      url: 'https://suttacentral.net/kp$1/en/sujato#kp$2$3'
    - pattern: '/(?:Snp|SNP|snp)[^\S\r\n]?([13]\.(?:[1-9]|1[0-2])|2\.(?:[1-9]|1[0-4])|4\.(?:[1-9]|1[0-6])|5\.(?:[1-9]|1[0-9]))(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/snp$1/en/sujato'
    - pattern: '/(?:Snp|SNP|snp)[^\S\r\n]?(([13]\.(?:[1-9]|1[0-2])|2\.(?:[1-9]|1[0-4])|4\.(?:[1-9]|1[0-6])|5\.(?:[1-9]|1[0-9])))(:[1-9](?:[0-9]+)?\.[1-9](?:[0-9]+)?)/'
      url: 'https://suttacentral.net/snp$1/en/sujato#snp$2$3'
    - pattern: '/(?:Snp|SNP|snp)[^\S\r\n]?(?:([1-5]):([1-9]|1[0-9]))(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/snp$1.$2/en/sujato'
    - pattern: '/(?:Thag|THAG|thag)[^\S\r\n]?(1\.(?:[1-9]|[1-9][0-9]|1[01][0-9]|120)|2\.(?:[1-9]|[1-4][0-9])|3\.(?:[1-9]|1[0-6])|[45]\.(?:[1-9]|1[0-2])|6\.(?:[1-9]|1[0-4])|7\.[1-5]|(?:8|17)\.[1-3]|(?:9|1[1389]|2[01])\.1|10\.[1-7]|1[245]\.[12]|16\.(?:[1-9]|10))(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/thag$1/en/sujato'
    - pattern: '/(?:Thag|THAG|thag)[^\S\r\n]?((1\.(?:[1-9]|[1-9][0-9]|1[01][0-9]|120)|2\.(?:[1-9]|[1-4][0-9])|3\.(?:[1-9]|1[0-6])|[45]\.(?:[1-9]|1[0-2])|6\.(?:[1-9]|1[0-4])|7\.[1-5]|(?:8|17)\.[1-3]|(?:9|1[1389]|2[01])\.1|10\.[1-7]|1[245]\.[12]|16\.(?:[1-9]|10)))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,2})/'
      url: 'https://suttacentral.net/thag$1/en/sujato#thag$2$3'
    - pattern: '/(?:Thig|THIG|thig)[^\S\r\n]?(1\.(?:[1-9]|1[0-8])|2\.(?:[1-9]|10)|[36]\.[1-8]|(?:[489]|1[0-24-6])\.1|5\.(?:[1-9]|1[0-2])|7\.[1-3]|13\.[1-5])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/thig$1/en/sujato'
    - pattern: '/(?:Thig|THIG|thig)[^\S\r\n]?((1\.(?:[1-9]|1[0-8])|2\.(?:[1-9]|10)|[36]\.[1-8]|(?:[489]|1[0-24-6])\.1|5\.(?:[1-9]|1[0-2])|7\.[1-3]|13\.[1-5]))(:[1-9](?:[0-9]+)?\.[1-9](?:[0-9]+)?)/'
      url: 'https://suttacentral.net/thig$1/en/sujato#thig$2$3'
    - pattern: '/(?:Ud|UD|ud)[^\S\r\n]?([1-8]\.(?:[1-9]|10))(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/ud$1/en/sujato'
    - pattern: '/(?:Ud|UD|ud)[^\S\r\n]?(([1-8]\.(?:[1-9]|10)))(:[1-9](?:[0-9]+)?\.[1-9](?:[0-9]+)?)/'
      url: 'https://suttacentral.net/ud$1/en/sujato#ud$2$3'
    - pattern: '/(?:Ud|UD|ud)[^\S\r\n]?(?:([1-8]):([1-9]|10))(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/ud$1.$2/en/sujato'
    - pattern: '/(?:MN|Mn|mn)[^\S\r\n]?([1-9]|[1-9][0-9]|1[0-4][0-9]|15[0-2])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/mn$1/en/sujato'
    - pattern: '/(?:MN|Mn|mn)[^\S\r\n]?(([1-9]|[1-9][0-9]|1[0-4][0-9]|15[0-2]))(:[1-9](?:[0-9-]+)?(?:\.[1-9](?:[0-9]+)?){1,2})/'
      url: 'https://suttacentral.net/mn$1/en/sujato#mn$2$3'
    - pattern: '/(?:SN|Sn|sn)[^\S\r\n]?(1\.(?:[1-9]|[1-7][0-9]|8[01])|2\.(?:[1-9]|[12][0-9]|30)|(?:[34]|11)\.(?:[1-9]|1[0-9]|2[0-5])|(?:5|2[5-8]|41)\.(?:[1-9]|10)|6\.(?:[1-9]|1[0-5])|(?:7|18)\.(?:[1-9]|1[0-9]|2[0-2])|(?:8|10|2[01])\.(?:[1-9]|1[0-2])|9\.(?:[1-9]|1[0-4])|12\.(?:[1-9]|[1-9][0-9]|1[0-9][0-9]|20[0-9]|21[0-3])|(?:13|4[04])\.(?:[1-9]|1[01])|14\.(?:[1-9]|[1-3][0-9])|(?:15|54)\.(?:[1-9]|1[0-9]|20)|(?:16|42)\.(?:[1-9]|1[0-3])|17\.(?:[1-9]|[1-3][0-9]|4[0-3])|19\.(?:[1-9]|1[0-9]|2[0-1])|22\.(?:[1-9]|[1-9][0-9]|1[0-5][0-9])|(?:23|30)\.(?:[1-9]|[1-3][0-9]|4[0-6])|24\.(?:[1-9]|[1-8][0-9]|9[0-6])|29\.(?:[1-9]|[1-4][0-9]|50)|31\.(?:[1-9]|[1-9][0-9]|10[0-9]|11[0-2])|32\.(?:[1-9]|[1-4][0-9]|5[0-7])|3[34]\.(?:[1-9]|[1-4][0-9]|5[0-5])|35\.(?:[1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-3][0-9]|24[0-8])|36\.(?:[1-9]|[12][0-9]|3[01])|37\.(?:[1-9]|[12][0-9]|3[0-4])|(?:3[89])\.(?:[1-9]|1[0-6])|43\.(?:[1-9]|[1-3][0-9]|4[0-4])|45\.(?:[1-9]|[1-9][0-9]|1[0-7][0-9]|180)|46\.(?:[1-9]|[1-9][0-9]|1[0-7][0-9]|18[0-4])|47\.(?:[1-9]|[1-9][0-9]|10[0-4])|48\.(?:[1-9]|[1-9][0-9]|1[0-6][0-9]|17[0-8])|(?:49|53)\.(?:[1-9]|[1-4][0-9]|5[0-4])|50\.(?:[1-9]|[1-9][0-9]|10[0-8])|51\.(?:[1-9]|[1-7][0-9]|8[0-6])|52\.(?:[1-9]|1[0-9]|2[0-4])|55\.(?:[1-9]|[1-6][0-9]|7[0-4])|56\.(?:[1-9]|[1-9][0-9]|1[0-2][0-9]|13[01]))(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/sn$1/en/sujato'
    - pattern: '/(?:SN|Sn|sn)[^\S\r\n]?((1\.(?:[1-9]|[1-7][0-9]|8[01])|2\.(?:[1-9]|[12][0-9]|30)|(?:[34]|11)\.(?:[1-9]|1[0-9]|2[0-5])|(?:5|2[5-8]|41)\.(?:[1-9]|10)|6\.(?:[1-9]|1[0-5])|(?:7|18)\.(?:[1-9]|1[0-9]|2[0-2])|(?:8|10|2[01])\.(?:[1-9]|1[0-2])|9\.(?:[1-9]|1[0-4])|12\.(?:[1-9]|[1-9][0-9]|1[0-9][0-9]|20[0-9]|21[0-3])|(?:13|4[04])\.(?:[1-9]|1[01])|14\.(?:[1-9]|[1-3][0-9])|(?:15|54)\.(?:[1-9]|1[0-9]|20)|(?:16|42)\.(?:[1-9]|1[0-3])|17\.(?:[1-9]|[1-3][0-9]|4[0-3])|19\.(?:[1-9]|1[0-9]|2[0-1])|22\.(?:[1-9]|[1-9][0-9]|1[0-5][0-9])|(?:23|30)\.(?:[1-9]|[1-3][0-9]|4[0-6])|24\.(?:[1-9]|[1-8][0-9]|9[0-6])|29\.(?:[1-9]|[1-4][0-9]|50)|31\.(?:[1-9]|[1-9][0-9]|10[0-9]|11[0-2])|32\.(?:[1-9]|[1-4][0-9]|5[0-7])|3[34]\.(?:[1-9]|[1-4][0-9]|5[0-5])|35\.(?:[1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-3][0-9]|24[0-8])|36\.(?:[1-9]|[12][0-9]|3[01])|37\.(?:[1-9]|[12][0-9]|3[0-4])|(?:3[89])\.(?:[1-9]|1[0-6])|43\.(?:[1-9]|[1-3][0-9]|4[0-4])|45\.(?:[1-9]|[1-9][0-9]|1[0-7][0-9]|180)|46\.(?:[1-9]|[1-9][0-9]|1[0-7][0-9]|18[0-4])|47\.(?:[1-9]|[1-9][0-9]|10[0-4])|48\.(?:[1-9]|[1-9][0-9]|1[0-6][0-9]|17[0-8])|(?:49|53)\.(?:[1-9]|[1-4][0-9]|5[0-4])|50\.(?:[1-9]|[1-9][0-9]|10[0-8])|51\.(?:[1-9]|[1-7][0-9]|8[0-6])|52\.(?:[1-9]|1[0-9]|2[0-4])|55\.(?:[1-9]|[1-6][0-9]|7[0-4])|56\.(?:[1-9]|[1-9][0-9]|1[0-2][0-9]|13[01])))(:[1-9](?:[0-9]+)?\.[1-9](?:[0-9]+)?)/'
      url: 'https://suttacentral.net/sn$1/en/sujato#sn$2$3'
    - pattern: '/(?:SN|Sn|sn)[^\S\r\n]?(?:([1-9]|[1-5][0-9]):([1-9]|[1-9][0-9]))(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/sn$1.$2/en/sujato'
    - pattern: '/(?:SN|Sn|sn)[^\S\r\n]?(?:([12]2|3[15]|4[5-8]|5[06]):([12][0-9][0-9]))(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/sn$1.$2/en/sujato'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Aa]s|[Bb]i[ -][Aa]s)[^\S\r\n]?([1-7])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-as1-7/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Aa]s|[Bb]i[ -][Aa]s)[^\S\r\n]?([1-7])(:[1-9](?:[0-9]+)?\.[1-9](?:[0-9]+)?)/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-as1-7/en/brahmali#pli-tv-bi-vb-as$1$2'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Nn]p|[Bb]i[ -][Nn]p)[^\S\r\n]?([1-9]|[12][0-9]|30)(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-np$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Nn]p|[Bb]i[ -][Nn]p)[^\S\r\n]?(([1-9]|[12][0-9]|30))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,3})/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-np$1/en/brahmali#pli-tv-bi-vb-np$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Pp]c|[Bb]i[ -][Pp]c)[^\S\r\n]?(9[1-3])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-pc91-93/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Pp]c|[Bb]i[ -][Pp]c)[^\S\r\n]?([1-9]|[1-9][0-9]|1[0-5][0-9]|16[0-6])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-pc$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Pp]c|[Bb]i[ -][Pp]c)[^\S\r\n]?(9[1-3])(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,3})/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-pc91-93/en/brahmali#pli-tv-bi-vb-pc$1$2'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Pp]c|[Bb]i[ -][Pp]c)[^\S\r\n]?(([1-9]|[1-9][0-9]|1[0-5][0-9]|16[0-6]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,3})/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-pc$1/en/brahmali#pli-tv-bi-vb-pc$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Pp]d|[Bb]i[ -][Pp]d)[^\S\r\n]?1(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-pd1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Pp]d|[Bb]i[ -][Pp]d)[^\S\r\n]?([2-8])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-pd2-8/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Pp]d|[Bb]i[ -][Pp]d)[^\S\r\n]?1(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,3})/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-pd1/en/brahmali#pli-tv-bi-vb-pd1$1'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Pp]d|[Bb]i[ -][Pp]d)[^\S\r\n]?([2-8])(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,3})/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-pd2-8/en/brahmali#pli-tv-bi-vb-pd$1$2'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Pp]j|[Bb]i[ -][Pp]j)[^\S\r\n]?([1-8])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-pj$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Pp]j|[Bb]i[ -][Pp]j)[^\S\r\n]?(([1-8]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,3})/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-pj$1/en/brahmali#pli-tv-bi-vb-pj$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Ss]k|[Bb]i[ -][Ss]k)[^\S\r\n]?([1-9]|[1-6][0-9]|7[0-5])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-sk$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Ss]k|[Bb]i[ -][Ss]k)[^\S\r\n]?(([1-9]|[1-6][0-9]|7[0-5]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,2})/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-sk$1/en/brahmali#pli-tv-bi-vb-sk$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Ss]s|[Bb]i[ -][Ss]s)[^\S\r\n]?([1-9]|1[0-7])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-ss$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]i[ -][Vv]b[ -][Ss]s|[Bb]i[ -][Ss]s)[^\S\r\n]?(([1-9]|1[0-7]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,2})/'
      url: 'https://suttacentral.net/pli-tv-bi-vb-ss$1/en/brahmali#pli-tv-bi-vb-ss$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Aa]s|[Bb]u[ -][Aa]s)[^\S\r\n]?([1-7])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-as1-7/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Aa]s|[Bb]u[ -][Aa]s)[^\S\r\n]?([1-7])(:[1-9](?:[0-9]+)?\.[1-9](?:[0-9]+)?)/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-as1-7/en/brahmali#pli-tv-bu-vb-as$1$2'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Aa]y|[Bb]u[ -][Aa]y)[^\S\r\n]?([12])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-ay$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Aa]y|[Bb]u[ -][Aa]y)[^\S\r\n]?(([12]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,2})/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-ay$1/en/brahmali#pli-tv-bu-vb-ay$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Nn]p|[Bb]u[ -][Nn]p)[^\S\r\n]?([1-9]|[12][0-9]|30)(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-np$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Nn]p|[Bb]u[ -][Nn]p)[^\S\r\n]?(([1-9]|[12][0-9]|30))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,3})/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-np$1/en/brahmali#pli-tv-bu-vb-np$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Pp]c|[Bb]u[ -][Pp]c)[^\S\r\n]?([1-9]|[1-8][0-9]|9[0-2])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-pc$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Pp]c|[Bb]u[ -][Pp]c)[^\S\r\n]?(([1-9]|[1-8][0-9]|9[0-2]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,3})/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-pc$1/en/brahmali#pli-tv-bu-vb-pc$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Pp]d|[Bb]u[ -][Pp]d)[^\S\r\n]?([1-4])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-pd$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Pp]d|[Bb]u[ -][Pp]d)[^\S\r\n]?(([1-4]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,3})/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-pd$1/en/brahmali#pli-tv-bu-vb-pd$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Pp]j|[Bb]u[ -][Pp]j)[^\S\r\n]?([1-4])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-pj$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Pp]j|[Bb]u[ -][Pp]j)[^\S\r\n]?(([1-4]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,3})/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-pj$1/en/brahmali#pli-tv-bu-vb-pj$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Ss]k|[Bb]u[ -][Ss]k)[^\S\r\n]?([1-9]|[1-6][0-9]|7[0-5])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-sk$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Ss]k|[Bb]u[ -][Ss]k)[^\S\r\n]?(([1-9]|[1-6][0-9]|7[0-5]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,2})/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-sk$1/en/brahmali#pli-tv-bu-vb-sk$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Ss]s|[Bb]u[ -][Ss]s)[^\S\r\n]?([1-9]|1[0-3])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-ss$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -][Bb]u[ -][Vv]b[ -][Ss]s|[Bb]u[ -][Ss]s)[^\S\r\n]?(([1-9]|1[0-3]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,3})/'
      url: 'https://suttacentral.net/pli-tv-bu-vb-ss$1/en/brahmali#pli-tv-bu-vb-ss$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -])?[Kk]d[^\S\r\n]?([1-9]|1[0-9]|2[0-2])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-kd$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -])?[Kk]d[^\S\r\n]?(([1-9]|1[0-9]|2[0-2]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,4})/'
      url: 'https://suttacentral.net/pli-tv-kd$1/en/brahmali#pli-tv-kd$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -])?[Pp]vr[^\S\r\n]?((?:[12])\.(?:[1-9]|1[0-6]))(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-pvr$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -])?[Pp]vr[^\S\r\n]?([3-9]|1[0-9]|2[01])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-pvr$1/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -])?[Pp]vr[^\S\r\n]?(((?:[12])\.(?:[1-9]|1[0-6])))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,2})/'
      url: 'https://suttacentral.net/pli-tv-pvr$1/en/brahmali#pli-tv-pvr$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -])?[Pp]vr[^\S\r\n]?(([3-9]|1[0-9]|2[01]))(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,2})/'
      url: 'https://suttacentral.net/pli-tv-pvr$1/en/brahmali#pli-tv-pvr$2$3'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -])?[Bb](u|i)[ -]?[Pp]m(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/pli-tv-b$1-pm/en/brahmali'
    - pattern: '/(?:[Pp][l]?i[ -][Tt]v[ -])?[Bb]((u|i))[ -]?[Pp]m(:[1-9](?:[0-9]+)?(?:\.[1-9](?:[0-9]+)?){1,2})/'
      url: 'https://suttacentral.net/pli-tv-b$1-pm/en/brahmali#pli-tv-b$2-pm$3'
    - pattern: '/(?:D[AĀ]|D[aā]|d[aā])[^\S\r\n]?([1-9]|[1-2][0-9]|30)(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/da$1/en/patton'
    - pattern: '/(?:M[AĀ]|M[aā]|m[aā])[^\S\r\n]?([1-9]|[1-9][0-9]|1[0-9][0-9]|2[01][0-9]|22[0-2])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/ma$1/en/patton'
    - pattern: '/(?:S[AĀ]|S[aā]|s[aā])[^\S\r\n]?([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-2][0-9][0-9]|13[0-5][0-9]|136[0-2])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/sa$1/en/patton'
    - pattern: '/(?:E[AĀ]|E[aā]|e[aā])[^\S\r\n]?(1\.1|(?:[2-489]|1[0-24-68]|2[1-79]|3[3-579]|4[023679]|5[01])\.(?:[1-9]|10)|(?:5|36|41)\.[1-5]|6\.[1-4]|(?:7|30)\.[1-3]|(?:13|28|45)\.[1-7]|(?:1[79]|31|44)\.(?:[1-9]|1[01])|20\.(?:[1-9]|1[0-3])|3[28]\.(?:[1-9]|1[0-2])|48\.[1-6]|52\.[1-9])(?:(?!:[0-9]))/'
      url: 'https://suttacentral.net/ea$1/en/patton'
  schema:
    name: linkify_rule
    properties:
      pattern:
        type: string
        required: true
      url:
        type: string
        required: true
excluded_tags:
  type: list
  list_type: compact
  default: "code|pre"
excluded_classes:
  type: list
  list_type: compact
  default: "onebox"
regex_substitute_or_character:
  default: "¦"
left_word_boundary:
  type: list
  list_type: compact
  default: "\\s|:|.|;|,|!|?|…|(|[|{|“|‘|=|—|–|-|/"
right_word_boundary:
  type: list
  list_type: compact
  default: "\\s|:|.|;|,|!|?|…|}|]|)|”|’|=|—|–|-|/"
